---
- name: Create .gnupg directory
  file:
    path: "$HOME/.gnupg"
    state: directory
    mode: "700"

- name: Creating gpg.conf
  copy:
    dest: "$HOME/.gnupg/gpg.conf"
    content: |
      use-agent

- name: Creating gpg-agent.conf
  copy:
    dest: "$HOME/.gnupg/gpg-agent.conf"
    content: |
      use-standard-socket
      pinentry-program /usr/local/bin/pinentry-mac
      enable-ssh-support

- name: Change permission on .gnupg directory
  file:
    path: "$HOME/.gnupg/gpg.conf"
    state: file
    mode: "600"

- name: Change permission on .gnupg directory
  file:
    path: "$HOME/.gnupg/gpg-agent.conf"
    state: file
    mode: "600"
