---
- hosts: all

  vars_files:
    - configs/default.config.yaml
    - configs/macos.config.yaml

  roles:
      - role: elliotweiser.osx-command-line-tools
        when: ansible_os_family == "Darwin"
        tags: [ 'macos' ]
      - role: geerlingguy.mac.homebrew
        when: ansible_os_family == "Darwin"
        tags: [ 'macos' ]

  tasks:

    - name: Install zsh and .zshrc
      import_tasks: tasks/zsh/zsh.yml
      tags:
        - zsh

    - name: Install GPG (macOS)
      import_tasks: tasks/gpg/gpg.yml
      when: ansible_os_family == "Darwin"

    - name: Install Git (macOS)
      import_tasks: tasks/git/macos.yml
      when: ansible_os_family == "Darwin"

    - name: Install Git (macOS)
      import_tasks: tasks/git/elementary.yml
      when: ansible_os_family == "elementary OS"

    - name: Import git config variables
      include_vars: configs/git.config.yaml
      tags:
        - git
