---
- hosts: all

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/configs/*.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_os_family == "Darwin"
      tags: ["macos"]
    - role: geerlingguy.mac.homebrew
      when: ansible_os_family == "Darwin"
      tags: ["macos"]

  tasks:
    - name: Ensure sudo password is correct
      command: echo "password is correct"
      become: true
      run_once: true
      tags:
        - always

    - name: Install dotfiles
      import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - always

    - name: Install and configure GPG
      import_tasks: tasks/gpg/main.yml
      tags:
        - gpg

    - name: Install Git (macOS)
      import_tasks: tasks/git/macos.yml
      when: ansible_os_family == "Darwin"
      tags:
        - git

    - name: Install Git (macOS)
      import_tasks: tasks/git/elementary.yml
      when: ansible_os_family == "elementary OS"
      tags:
        - git

    - name: Configure Git
      import_tasks: tasks/git/configure.yml
      tags:
        - git

    - name: Install pyenv
      import_tasks: tasks/pyenv.yml
      tags:
        - python

    - name: Install PyCharm
      import_tasks: tasks/pycharm/elementary.yml
      when: ansible_os_family == "elementary OS"
      tags:
        - pycharm
