---
- hosts: all

  vars_files:
    - configs/default.config.yaml
    - configs/macos.config.yaml

  tasks:
    - name: Ansible setup validataion.
      include_tasks: tasks/ansible-setup.yaml
      tags:
        - always

    - name: Configure Mac OS and install essential packages.
      include_tasks: tasks/macos.yaml
      when: ansible_os_family == "Darwin"
      tags:
        - macos
