---
- hosts: all

  vars_files:
    - configs/default.config.yaml
    - configs/macos.config.yaml

  roles:
      - role: elliotweiser.osx-command-line-tools
        tags: [ 'macos' ]
      - role: geerlingguy.mac.homebrew
        tags: [ 'macos' ]

  tasks:
    - name: Install or update Git
      include_tasks: tasks/git/git.yml
      tags:
        - git

#    - name: Configure macOS and install essesntial packages.
#      include_tasks: tasks/macos.yaml
#      when: ansible_os_family == "Darwin"
#      tags:
#        - macos
#
#    - name: Configure zsh.
#      include_tasks: tasks/zsh.yaml
#      when: ansible_os_family == "Darwin"
#
#    - name: Configure Python.
#      include_tasks: tasks/python.yaml
#
#    - name: Configure VS Code.
#      include_tasks: tasks/vscode.yaml
