---
- hosts: all

  vars_files:
    - configs/default.config.yaml
    - configs/macos.config.yaml

  tasks:
    - name: Ansible setup validataion.
      include_tasks: tasks/ansible.yaml
      tags:
        - always

#    - name: Configure Mac OS and install essential packages.
#      include_tasks: tasks/macos.yaml
#      when: ansible_os_family == "Darwin"
#      tags:
#        - macos
#
#    - name: Configure zsh.
#      include_tasks: tasks/zsh.yaml
#      when: ansible_os_family == "Darwin"
#
#    - name: Configure Python.
#      include_tasks: tasks/python.yaml
#
#    - name: Configure VS Code.
#      include_tasks: tasks/vscode.yaml
