[tools]
oxfmt = "latest"
shellcheck = "latest"
claude = "latest"
codex = "latest"
difftastic = "latest"
just = "latest"
node = "latest"
rtk = "latest"

[settings]
lockfile = true
minimum_release_age = "7d"
