mise_args := ""

mise-clean:
    mise prune {{ mise_args }} --yes && \
    mise cache {{ mise_args }} clean && \
    mise cache {{ mise_args }} prune

mise-install:
    mise install {{ mise_args }}

mise-upgrade:
    mise self-update
    mise upgrade {{ mise_args }} --bump

mise-lock:
    mise lock {{ mise_args }} --global

mise-use tool:
    mise use {{ mise_args }} --global {{ tool }}

fix:
    mise fmt --cd ${HOME}/.config/mise
