---
- name: Ensure that become password is correct.
  command: echo "Become password is correct"
  become: true
  changed_when: false
  tags:
    - always

- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: true

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
