---
- name: Ensure that become password is correct.
  command: echo "Become password is correct!"
  become: true
  changed_when: false
  register: become_password_correct
  failed_when: become_password_correct.stdout != "Become password is correct!"
  tags:
    - always

- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: true

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
