---
- name: Delete .hyper.js if exists.
  file:
    path: "$HOME/.hyper.js"
    state: absent

- name: Install .hyper.js
  file:
    src: "{{ dotfiles_repo_local }}/dotfiles/.hyper.js"
    dest: "$HOME/.hyper.js"
    state: link
    mode: 0644
  become: false
