---
- name: Ensure pyenv is installed.
  command: which pyenv
  register: pyenv_version_installed
  changed_when: false
  ignore_errors: true

- name: Get pyenv installer.
  get_url: 
    url: https://pyenv.run
    dest: $HOME/pyenv-installer
    mode: u+rx
  when: pyenv_version_installed.rc != 0

- name: Install pyenv.
  command: $HOME/pyenv-installer
  when: pyenv_version_installed.rc != 0

- name: Get pyenv installer.
  file: 
    path: $HOME/pyenv-installer
    state: absent
  when: pyenv_version_installed.rc != 0

- name: Check installed versions of Python.
  command: pyenv versions --bare
  register: python_installed_versions
  changed_when: python_version not in python_installed_versions.stdout_lines

- name: Install Python.
  command: "pyenv install --force {{ python_version }}"
  when: python_version not in python_installed_versions.stdout_lines

- name: Check Python global verion.
  command: pyenv global
  register: python_installed_global_version
  changed_when: python_installed_global_version != python_version

- name: Set Python global version.
  command: "pyenv global {{ python_version }}"
  when: python_installed_global_version != python_version
