- name: Install VS Code extensions.
  command: "code --install-extension {{ item }}"
  changed_when: false
  with_items: "{{ vscode.extensions }}"

- name: Remove install VS Code preferences.
  file:
    path: "$HOME/Library/Application\ Support/Code/User/settings.json"
    state: absent

- name: Install VS Code preferences.
  file:
    src: "{{ dotfiles_repo_local }}/dotfiles/.vscode-preferences.json"
    dest: "$HOME/Library/Application\ Support/Code/User/settings.json"
    state: link
    mode: 0644
