- name: Install zsh plugins with antibody.
  shell:
    cmd: antibody bundle < dotfiles/zsh_plugins.txt > dotfiles/.zsh_plugins
  changed_when: false

- name: Install zsh (elementary OS)
  become: true
  apt:
    name: zsh
    state: latest
  when: ansible_os_family == "elementary OS"

- name: Link zsh related dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local }}/dotfiles/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
    mode: 0644
  with_items: "{{ zsh_dotfiles_files }}"
  become: false
