brew "ca-certificates"
brew "webp"
brew "git"
brew "libheif"
brew "mise"
brew "openssh"
brew "tcl-tk"
brew "texlive"
brew "zsh"
brew "zsh-history-substring-search"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-sf-mono-nerd-font-ligaturized"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
