---
downloads: ~/.ansible-downloads/
dotfiles_repo_local: $HOME/github/dotfiles

zsh_dotfiles_files:
  - .zshrc
  - .environment
  - .zsh_plugins
  - .aliases
  - .starship.toml

python_version: 3.8.8
vscode:
  extensions:
    - codezombiech.gitignore
    - GitHub.github-vscode-theme
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - VisualStudioExptTeam.vscodeintellicode
