---
dotfiles_repo_local: $HOME/personal/github/dotfiles

global_gitconfig_file: .gitconfig
local_gitconfig_files:
  - personal.gitconfig
  - work.gitconfig

zsh_dotfiles_files:
  - .zshrc
  - .environment
  - .zsh_plugins
  - .aliases

python_version: 3.8.8
vscode:
  extensions:
    - codezombiech.gitignore
    - GitHub.github-vscode-theme
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - VisualStudioExptTeam.vscodeintellicode
