---
dotfiles_repo_local: $HOME/personal/github/dotfiles

zsh_dotfiles_files:
  - .zshrc
  - .environment
  - .zsh_plugins
  - .aliases

python_version: 3.10.0
pycharm_version: 2021.2.3
pycharm_edition: professional

vscode:
  extensions:
    - codezombiech.gitignore
    - GitHub.github-vscode-theme
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - VisualStudioExptTeam.vscodeintellicode
