osx_script: "dotfiles/.macos --no-restart"
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - homebrew/cask-versions
homebrew_cask_appdir: /Applications
homebrew_packages:
  essential:
    - bash
    - zsh
    - coreutils
    - moreutils
    - findutils
    - antibody
    - wget
    - gnupg
    - openssh
    - openssl
    - readline 
    - sqlite3 
    - xz 
    - zlib
  development:
    - git
    - starship
homebrew_cask_packages:
  fonts:
    - font-inter
    - font-jetbrains-mono-nerd-font
  tools:
    - stats
    - 1password
    - kap
    - grammarly
    - logitech-g-hub
    - logitech-firmwareupdatetool
  communication:
    - discord
    - microsoft-outlook
    - microsoft-teams
    - slack
    - telegram
  media:
    - spotify
  development:
    - hyper
    - firefox-developer-edition
    - chromium
    - docker
    - tunnelblick
    - visual-studio-code
    - notion
    - miro
    - figma
touch_id_sudo_line: "auth       sufficient     pam_tid.so"
