osx_script: "dotfiles/.macos --no-restart"
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - homebrew/cask-versions
homebrew_cask_appdir: /Applications
homebrew_installed_packages:
  - bash
  - zsh
  - coreutils
  - moreutils
  - findutils
  - antibody
  - wget
  - gnupg
  - openssh
  - openssl
  - readline
  - sqlite3
  - xz
  - zlib
  - git
  - starship
  - gpg2
  - gnupg
  - pinentry-mac
homebrew_cask_apps:
  - font-inter
  - font-jetbrains-mono-nerd-font
  - stats
  - 1password
  - kap
  - grammarly
  - discord
  - microsoft-teams
  - slack
  - telegram
  - spotify
  - brave
  - chromium
  - tunnelblick
  - visual-studio-code
  - notion
touch_id_sudo_line: "auth       sufficient     pam_tid.so"
